export const aboutMe = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "About Me",
  description:
    "I'm an aspiring front-end developer working with the fine folks at the UNC Chapel Hill Coding Bootcamp with the intention of switching careers. I've worked as a sales representative in the craft beer and wine industry for seven years and before that I had seen my fair share of both sides of the bar at some great Raleigh restaurants. When I have free time I enjoy playing and collecting video games and records, skateboarding and taking our dog on adventures.",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/ben-and-oakley.png"),
  alt: "man and dog",
  dark: true,
  primary: true,
  darkText: false,
  link: "https://github.com/benwofford",
  deployLink: "https://www.linkedin.com/in/ben-wofford-9a5781217",
};

export const projectOne = {
  id: "projects",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Group Project",
  headline: "Pokemon TCG Binder",
  description:
    "We built a website that pulls in Pokemon TCG API data to provide up-to-date market prices along with the ability to create an account and save a binder of cards.",
  buttonLabel: "Github",
  imgStart: true,
  img: require("../../images/PTC.png"),
  alt: "PTC main page",
  dark: false,
  primary: false,
  darkText: true,
  link: "https://github.com/McTastic/PTC-Binder",
  deployLink: "https://ptc-binder.herokuapp.com/",
};

export const projectTwo = {
  id: "",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Group Project",
  headline: "sipNshow",
  description:
    "We built an application that pulls in two different API's to fetch live music show information and compare it to local breweries in the area to visit before or after the show.",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/sipNshow-search.png"),
  alt: "sipNshow search page",
  dark: true,
  primary: true,
  darkText: false,
  link: "https://github.com/kmwine02/project01",
  deployLink: "https://kmwine02.github.io/project01/",
};

export const projectThree = {
  id: "",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Solo Build",
  headline: "Note Taker App",
  description:
    "This project's purpose is to give the user a platform to create notes to organize a busy mind.",
  buttonLabel: "Github",
  imgStart: true,
  img: require("../../images/note-taker-main.png"),
  alt: "note taker application",
  dark: false,
  primary: false,
  darkText: true,
  link: "https://github.com/benwofford/note-taker",
  deployLink: "https://stark-hollows-89499.herokuapp.com/",
};

export const projectFour = {
  id: "",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Solo Build",
  headline: "Fitness Tracker App",
  description:
    "This application allows the user to create, track and view daily workouts.",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/fitness-tracker.png"),
  alt: "fitness tracker dashboardbudget",
  dark: true,
  primary: true,
  darkText: false,
  link: "https://github.com/benwofford/fitness-tracker",
  deployLink: "https://evening-escarpment-68052.herokuapp.com/",
};

export const projectFive = {
  id: "",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Solo Build",
  headline: "Budget Tracking App",
  description:
    "This application was created to allow one to track their spending even if they happen to go offline.",
  buttonLabel: "Github",
  imgStart: true,
  img: require("../../images/budget.png"),
  alt: "budget tracking app",
  dark: false,
  primary: false,
  darkText: true,
  link: "https://github.com/benwofford/progressive-budget-app",
  deployLink: "https://stark-beach-18345.herokuapp.com/",
};

export const projectSix = {
  id: "projects",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Solo Build",
  headline: "Random Password Generator",
  description:
    "This random password generator provides random strings of characters chosen by the user to create a safe and secure password.",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/password-generator.png"),
  alt: "password generator",
  dark: true,
  primary: true,
  darkText: false,
  link: "https://github.com/benwofford/Password-Generator",
  deployLink: "https://benwofford.github.io/Password-Generator/",
};

export const contactMe = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Contact Me",
  headline: "I'd love to hear from you!",
  description: "📞: 919-789-1587 📧:benwofforddev@gmail.com",
  buttonLabel: "Say hi!",
  imgStart: true,
  img: require("../../images/contact.png"),
  alt: "contact",
  dark: false,
  primary: false,
  darkText: true,
  link: "/#/contactform",
};
